apiVersion: apps/v1
kind: Deployment
metadata:
  name: kezdo-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kezdo
  template:
    metadata:
      labels:
        app: kezdo
    spec:
      containers:
      - name: kontener
        image: ocsenasbence/go-http-server:v2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"