apiVersion: v1
kind: Pod
metadata:
  name: kezdo-app-v2
  labels:
    app: kezdo
spec:
  containers:
  - name: kontener
    image: ocsenasbence/go-http-server:v2
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
