apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kezdo-app-monitor
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: kezdo
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: web